### PR TITLE
Removes x2 multiplier on num_posts

### LINKED ISSUE #64: Widget "Number of posts to show" is doubled in widget output
Currently, on updated plugin, the field in the widget to set max rows isn't working, my site is showing double of what number I set in this field.

### PR DESCRIPTION
**Pull request by wadehammes**
Fixes #64

### CODE REVIEW

**Comment by aschweigert** [comment]
seems odd that would have been in there all this time...do we know where that came from originally? @benlk?

**Comment by benlk** [comment]
Yeah, that 2x modifier is weird. My best guess is that maybe it was introduced with code borrowed from the Largo Related Posts Widget, where it would've been necessary because of how Largo_Related trimmed the number of posts down.

**Comment by rclachance** [comment]
yeah, introduced in the second to last commit https://github.com/wadehammes/Google-Analytics-Popular-Posts/commit/26f718a69ff10c7393578e42c8e2e24ed669adf1#diff-b7ae0382593cd8bbd542e40639bf1182

**Comment by benlk** [comment]
I wonder what we have that's modifying that filter.

**Comment by rclachance** [comment]
thanks for the patch, @wadehammes!

**Comment by wadehammes** [comment]
@rclations no problem guys!

**Comment by benlk** [comment]
As far as I can tell, we have used that filter for one thing: https://github.com/religionnews/theme-rns/blob/master/inc/widgets.php#L25-L46

Which does not require the `* 2`.

**Pull request merged**
